# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tile.ui',
# licensing of 'tile.ui' applies.
#
# Created: Wed May  8 22:38:08 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Tile(object):
    def setupUi(self, Tile):
        Tile.setObjectName("Tile")
        Tile.resize(400, 300)
        self.gridLayoutWidget = QtWidgets.QWidget(Tile)
        self.gridLayoutWidget.setEnabled(True)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 301))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.box_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.box_5.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.box_5.setFont(font)
        self.box_5.setFrameShape(QtWidgets.QFrame.Box)
        self.box_5.setAlignment(QtCore.Qt.AlignCenter)
        self.box_5.setObjectName("box_5")
        self.gridLayout.addWidget(self.box_5, 1, 2, 1, 1)
        self.box_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.box_4.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.box_4.setFont(font)
        self.box_4.setFrameShape(QtWidgets.QFrame.Box)
        self.box_4.setAlignment(QtCore.Qt.AlignCenter)
        self.box_4.setObjectName("box_4")
        self.gridLayout.addWidget(self.box_4, 1, 1, 1, 1)
        self.box_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.box_1.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.box_1.setFont(font)
        self.box_1.setFrameShape(QtWidgets.QFrame.Box)
        self.box_1.setAlignment(QtCore.Qt.AlignCenter)
        self.box_1.setObjectName("box_1")
        self.gridLayout.addWidget(self.box_1, 0, 1, 1, 1)
        self.box_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.box_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.box_2.setFont(font)
        self.box_2.setFrameShape(QtWidgets.QFrame.Box)
        self.box_2.setAlignment(QtCore.Qt.AlignCenter)
        self.box_2.setObjectName("box_2")
        self.gridLayout.addWidget(self.box_2, 0, 2, 1, 1)
        self.box_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.box_0.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.box_0.setFont(font)
        self.box_0.setFrameShape(QtWidgets.QFrame.Box)
        self.box_0.setAlignment(QtCore.Qt.AlignCenter)
        self.box_0.setObjectName("box_0")
        self.gridLayout.addWidget(self.box_0, 0, 0, 1, 1)
        self.box_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.box_3.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.box_3.setFont(font)
        self.box_3.setFrameShape(QtWidgets.QFrame.Box)
        self.box_3.setAlignment(QtCore.Qt.AlignCenter)
        self.box_3.setObjectName("box_3")
        self.gridLayout.addWidget(self.box_3, 1, 0, 1, 1)
        self.box_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.box_6.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.box_6.setFont(font)
        self.box_6.setFrameShape(QtWidgets.QFrame.Box)
        self.box_6.setAlignment(QtCore.Qt.AlignCenter)
        self.box_6.setObjectName("box_6")
        self.gridLayout.addWidget(self.box_6, 2, 0, 1, 1)
        self.box_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.box_7.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.box_7.setFont(font)
        self.box_7.setFrameShape(QtWidgets.QFrame.Box)
        self.box_7.setAlignment(QtCore.Qt.AlignCenter)
        self.box_7.setObjectName("box_7")
        self.gridLayout.addWidget(self.box_7, 2, 1, 1, 1)
        self.box_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.box_8.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.box_8.setFont(font)
        self.box_8.setFrameShape(QtWidgets.QFrame.Box)
        self.box_8.setAlignment(QtCore.Qt.AlignCenter)
        self.box_8.setObjectName("box_8")
        self.gridLayout.addWidget(self.box_8, 2, 2, 1, 1)

        self.retranslateUi(Tile)
        QtCore.QMetaObject.connectSlotsByName(Tile)

    def retranslateUi(self, Tile):
        Tile.setWindowTitle(QtWidgets.QApplication.translate("Tile", "Form", None, -1))
        self.box_5.setText(QtWidgets.QApplication.translate("Tile", "TextLabel", None, -1))
        self.box_4.setText(QtWidgets.QApplication.translate("Tile", "TextLabel", None, -1))
        self.box_1.setText(QtWidgets.QApplication.translate("Tile", "TextLabel", None, -1))
        self.box_2.setText(QtWidgets.QApplication.translate("Tile", "TextLabel", None, -1))
        self.box_0.setText(QtWidgets.QApplication.translate("Tile", "TextLabel", None, -1))
        self.box_3.setText(QtWidgets.QApplication.translate("Tile", "TextLabel", None, -1))
        self.box_6.setText(QtWidgets.QApplication.translate("Tile", "TextLabel", None, -1))
        self.box_7.setText(QtWidgets.QApplication.translate("Tile", "TextLabel", None, -1))
        self.box_8.setText(QtWidgets.QApplication.translate("Tile", "TextLabel", None, -1))

